# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_32BIT),y)
	dtb-$(CONFIG_SOC_SCR) += vcu118_scr5_rv32_l2.dtb
else
	dtb-$(CONFIG_SOC_SCR) += vcu118_scr9_l3.dtb vcu118_scr7_l2.dtb vcu118_scr5_rv64_l2.dtb
endif
